name = "futils"
version = "0.2.1"
license = "Mit"
author = "Nkzono99"
maintainer = "210x218x@gsuite.kobe-u.ac.jp"
copyright = "Copyright 2022, Nkzono99"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = true
