name = "futils"
version = "0.2.2"
license = "Mit"
author = "Nkzono99"
maintainer = "210x218x@gsuite.kobe-u.ac.jp"
copyright = "Copyright 2022, Nkzono99"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[dependencies]
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"

[install]
library = true
